# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-01 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('std', models.FloatField()),
                ('daily_posted', models.FloatField()),
                ('demand', models.FloatField()),
                ('current_price', models.FloatField()),
                ('current_quantity', models.IntegerField()),
            ],
        ),
    ]
