# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-02 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0002_auto_20161202_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='current_price',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='item',
            name='current_quantity',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='item',
            name='daily_posted',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='item',
            name='demand',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='item',
            name='std',
            field=models.FloatField(default=-1),
        ),
    ]
