# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-02 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0003_auto_20161202_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='buy_for',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='item',
            name='sell_for',
            field=models.FloatField(default=-1),
        ),
    ]
