# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-02 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0004_auto_20161202_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('time_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField()),
            ],
        ),
    ]
